---
- hosts: localhost
  become: true
  tasks:
    - name: install nodejs for LSP language servers support in neovim
      package: name=nodejs
    - name: Verify ctags has been installed
      package: name=ctags
